--- #YAML:1.0
name:                Test-Warn
version:             0.11
abstract:            Perl extension to test methods for warnings
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Array::Compare:                0
    File::Spec:                    0
    Sub::Uplevel:                  0.12
    Test::Builder:                 0.13
    Test::Builder::Tester:         1.02
    Test::Exception:               0
    Test::More:                    0
    Tree::DAG_Node:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alexandr Ciornii <alexchorny@gmail.com>
